#!/bin/bash

createNODE()
{
	ARG="$1"
	if [ ! -z "$ARG" ]; then
		mkdir $ARG
		mkdir $ARG/public
		mkdir $ARG/public/js
		mkdir $ARG/public/js/libs
		mkdir $ARG/public/css
		mkdir $ARG/public/img
		mkdir $ARG/app
		mkdir $ARG/app/controllers
		mkdir $ARG/app/models
		mkdir $ARG/views
		touch $ARG/server.js
		touch $ARG/views/index.html
		touch $ARG/public/css/style.css
		touch $ARG/public/js/script.js
		touch $ARG/public/js/plugins.js
		wget -O $ARG/public/js/libs/modernizr-2.5.3.js http://www.modernizr.com/downloads/modernizr-2.5.3.js
		wget -O $ARG/public/js/libs/underscore.js http://documentcloud.github.com/underscore/underscore-min.js
		wget -O $ARG/public/js/libs/backbone.js http://documentcloud.github.com/backbone/backbone-min.js
		wget -O $ARG/public/js/libs/jquery-1.7.1.min.js http://code.jquery.com/jquery-1.7.1.min.js
		echo "$ARG NODE boiler was made with directories and files!"
	fi
}